config/routes.rb
Neurock::Application.routes.draw do
  get "main/index"
  get "post_page/:id" => "main#post", :as => :post_page 

  resources :block_kinds

  resources :admins

  root :to => 'main#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  
  has_many :posts
  has_many :pages

  attr_accessible :age, :email, :lastname, :name

end

app/models/block_kind.rb
class BlockKind < ActiveRecord::Base
  
  has_many :page_block_kinds

  attr_accessible :description, :title

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :parent, :polymorphic => true
  attr_accessible :comment, :parent_id, :parent_kind
end

app/models/page.rb
class Page < ActiveRecord::Base
	
  belongs_to :admin

  has_many :comments, :as => :parent  
  has_many :page_block_kinds

  attr_accessible :title

end

app/models/page_block_kind.rb
class PageBlockKind < ActiveRecord::Base
  belongs_to :page
  belongs_to :block_kind
  # attr_accessible :title, :body
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :admin

  has_many :comments, :as => :parent

  attr_accessible :description, :title
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :comments
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :lastname, :bio
  # attr_accessible :title, :body
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  # GET /admins
  # GET /admins.json
  def index
    @admins = Admin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
    @admin = Admin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin }
    end
  end

  # GET /admins/new
  # GET /admins/new.json
  def new
    @admin = Admin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin }
    end
  end

  # GET /admins/1/edit
  def edit
    @admin = Admin.find(params[:id])
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(params[:admin])

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: 'Admin was successfully created.' }
        format.json { render json: @admin, status: :created, location: @admin }
      else
        format.html { render action: "new" }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admins/1
  # PUT /admins/1.json
  def update
    @admin = Admin.find(params[:id])

    respond_to do |format|
      if @admin.update_attributes(params[:admin])
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin = Admin.find(params[:id])
    @admin.destroy

    respond_to do |format|
      format.html { redirect_to admins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/block_kinds_controller.rb
class BlockKindsController < ApplicationController
  # GET /block_kinds
  # GET /block_kinds.json
  def index
    @block_kinds = BlockKind.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @block_kinds }
    end
  end

  # GET /block_kinds/1
  # GET /block_kinds/1.json
  def show
    @block_kind = BlockKind.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @block_kind }
    end
  end

  # GET /block_kinds/new
  # GET /block_kinds/new.json
  def new
    @block_kind = BlockKind.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @block_kind }
    end
  end

  # GET /block_kinds/1/edit
  def edit
    @block_kind = BlockKind.find(params[:id])
  end

  # POST /block_kinds
  # POST /block_kinds.json
  def create
    @block_kind = BlockKind.new(params[:block_kind])

    respond_to do |format|
      if @block_kind.save
        format.html { redirect_to @block_kind, notice: 'Block kind was successfully created.' }
        format.json { render json: @block_kind, status: :created, location: @block_kind }
      else
        format.html { render action: "new" }
        format.json { render json: @block_kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /block_kinds/1
  # PUT /block_kinds/1.json
  def update
    @block_kind = BlockKind.find(params[:id])

    respond_to do |format|
      if @block_kind.update_attributes(params[:block_kind])
        format.html { redirect_to @block_kind, notice: 'Block kind was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @block_kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /block_kinds/1
  # DELETE /block_kinds/1.json
  def destroy
    @block_kind = BlockKind.find(params[:id])
    @block_kind.destroy

    respond_to do |format|
      format.html { redirect_to block_kinds_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
  	@posts = Post.limit(5).order("id DESC")
  end

  def post
  	@post = Post.find(params[:id])
  end

  def previous_posts(post_id)
  	@posts = Post.where("id < ?", post_id).order("id DESC").limit(5)
  end

  def next_posts(post_id)
  	posts_tmp = Post.where("id > ?", post_id).order("id ASC").limit(5)
  	@posts = []
  	posts_tmp.map{ |post|
  		@posts << post
  	}
  	@posts = @posts.reverse
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/block_kinds_helper.rb
module BlockKindsHelper
end

app/helpers/main_helper.rb
module MainHelper

	def print_navigation_menus(posts)
		pre = link_to "Previous", "#"
		nex = link_to "Next", "#"

		pre + " | " + nex
	end

end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<h1>Listing admins</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Lastname</th>
    <th>Email</th>
    <th>Age</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admins.each do |admin| %>
  <tr>
    <td><%= admin.name %></td>
    <td><%= admin.lastname %></td>
    <td><%= admin.email %></td>
    <td><%= admin.age %></td>
    <td><%= link_to 'Show', admin %></td>
    <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
    <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @admin.name %>
</p>

<p>
  <b>Lastname:</b>
  <%= @admin.lastname %>
</p>

<p>
  <b>Email:</b>
  <%= @admin.email %>
</p>

<p>
  <b>Age:</b>
  <%= @admin.age %>
</p>


<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/application/_post.html.erb
<div>
	<div>
		<%= post.title %>
	</div>

	<div>
		<%= raw truncate(post.description, :length => 50, :omission => ("..." + link_to("View more", post_page_path(post.id)))) %>
	</div>

	<hr />
</div>

app/views/block_kinds/_form.html.erb
<%= form_for(@block_kind) do |f| %>
  <% if @block_kind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@block_kind.errors.count, "error") %> prohibited this block_kind from being saved:</h2>

      <ul>
      <% @block_kind.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/block_kinds/edit.html.erb
<h1>Editing block_kind</h1>

<%= render 'form' %>

<%= link_to 'Show', @block_kind %> |
<%= link_to 'Back', block_kinds_path %>

app/views/block_kinds/index.html.erb
<h1>Listing block_kinds</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @block_kinds.each do |block_kind| %>
  <tr>
    <td><%= block_kind.title %></td>
    <td><%= block_kind.description %></td>
    <td><%= link_to 'Show', block_kind %></td>
    <td><%= link_to 'Edit', edit_block_kind_path(block_kind) %></td>
    <td><%= link_to 'Destroy', block_kind, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Block kind', new_block_kind_path %>

app/views/block_kinds/new.html.erb
<h1>New block_kind</h1>

<%= render 'form' %>

<%= link_to 'Back', block_kinds_path %>

app/views/block_kinds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @block_kind.title %>
</p>

<p>
  <b>Description:</b>
  <%= @block_kind.description %>
</p>


<%= link_to 'Edit', edit_block_kind_path(@block_kind) %> |
<%= link_to 'Back', block_kinds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Neurock</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<div>
	<%= render :partial => "post", :collection => @posts %>
</div>

<div>
	<%= print_navigation_menus(@posts) %>
</div>

app/views/main/post.html.erb
<div>
	<div>
		<%= @post.title %>
	</div>

	<div>
		<%= @post.description %>
	</div>
</div>